modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="noob"
version="1.1"
displayName="The Game of Noobs"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/AwesomeKalin/the-game-of-noobs-1.15"
authors="AwesomeKalin55, AwesomeFootball 123"
description='''
The mod for noobs. DO NOT USE IF YOU ARE A PRO
'''

[[dependencies.noob]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



